// =======================================================================
//   LÓTUM — POLÍTICA DE PRIVACIDAD (datos)
// =======================================================================
const PRIVACIDAD_DATA = {
  meta: {
    version: 'Versión 1.0',
    note: 'Documento de trabajo para revisión legal',
    updatedAt: '27 de noviembre de 2026',
    jurisdiction: 'Ley 25.326 — Argentina',
    legalEntity: 'Lucas Andrade (responsable provisorio)',
    cuit: 'En trámite',
    address: 'Mar del Plata, Provincia de Buenos Aires',
    contactEmail: 'contacto@lotum.com.ar',
  },
  preamble: `La presente Política de Privacidad y Protección de Datos Personales (en adelante, la "Política") describe la forma en que LÓTUM recolecta, utiliza, almacena, protege, transfiere y, en general, trata los datos personales de los Usuarios que acceden, se registran y utilizan la plataforma digital LÓTUM (en adelante, la "Plataforma").

El responsable del tratamiento de los datos personales es LUCAS ANDRADE (responsable provisorio en proceso de constitución de Lótum S.R.L.), CUIT en trámite, con domicilio legal en Mar del Plata, Provincia de Buenos Aires, República Argentina. Correo de contacto: contacto@lotum.com.ar.

LÓTUM inscribirá sus bases de datos ante el Registro Nacional de Bases de Datos Personales de la Agencia de Acceso a la Información Pública (AAIP), conforme lo exige la Ley 25.326.`,
  acceptanceWarning: 'AL UTILIZAR LA PLATAFORMA, EL USUARIO MANIFIESTA HABER LEÍDO, COMPRENDIDO Y ACEPTADO LA PRESENTE POLÍTICA DE PRIVACIDAD, PRESTANDO SU CONSENTIMIENTO LIBRE, EXPRESO, PREVIO E INFORMADO AL TRATAMIENTO DE SUS DATOS PERSONALES EN LOS TÉRMINOS AQUÍ DESCRIPTOS.',
  sections: [
    {
      id: 'marco-legal',
      number: '1',
      title: 'Marco legal aplicable',
      content: [
        { type: 'p', text: 'Esta Política se rige principalmente por:' },
        { type: 'ul', items: [
          'Ley N° 25.326 de Protección de Datos Personales.',
          'Decreto Reglamentario N° 1558/2001.',
          'Disposiciones y Resoluciones de la Agencia de Acceso a la Información Pública (AAIP).',
          'Ley N° 26.951 (Registro "No Llame").',
          'Ley N° 27.275 de Acceso a la Información Pública.',
          'Ley N° 25.246 y modificatorias (Prevención del Lavado de Activos y Financiamiento del Terrorismo) en lo pertinente.',
          'Resoluciones de la Unidad de Información Financiera (UIF).',
          'Disposiciones complementarias del Banco Central de la República Argentina (BCRA) y de la Comisión Nacional de Valores (CNV) cuando resulten aplicables.',
          'Estándares internacionales de mejores prácticas (Reglamento General de Protección de Datos — RGPD/GDPR — de la Unión Europea, adoptados a título orientativo).',
        ]},
      ],
    },
    {
      id: 'definiciones',
      number: '2',
      title: 'Definiciones',
      content: [
        { type: 'definitions', items: [
          ['Datos Personales', 'información de cualquier tipo referida a personas humanas identificadas o identificables.'],
          ['Datos Sensibles', 'datos personales que revelan origen racial o étnico, opiniones políticas, convicciones religiosas, filosóficas o morales, afiliación sindical, información referente a la salud o a la vida sexual.'],
          ['Datos Biométricos', 'datos derivados de características físicas o conductuales que permiten la identificación unívoca de una persona (rostro, huella dactilar, iris, voz, etc.).'],
          ['Tratamiento', 'operaciones y procedimientos sistemáticos que permitan la recolección, conservación, ordenación, almacenamiento, modificación, evaluación, bloqueo, cesión, transferencia y, en general, el procesamiento de Datos Personales.'],
          ['Titular', 'la persona humana cuyos datos son objeto de tratamiento.'],
          ['Responsable', 'LÓTUM, en su carácter de titular de la base de datos.'],
          ['Encargado', 'persona humana o jurídica que trata datos por cuenta del Responsable.'],
          ['Consentimiento', 'manifestación libre, expresa, previa e informada del Titular para el tratamiento de sus datos.'],
          ['AAIP', 'Agencia de Acceso a la Información Pública, autoridad de aplicación de la Ley 25.326.'],
        ]},
      ],
    },
    {
      id: 'datos-recolectados',
      number: '3',
      title: 'Datos personales que recolectamos',
      content: [
        { type: 'p', text: 'LÓTUM recolecta las siguientes categorías de datos:' },
        { type: 'h3', text: '3.1. Datos de identificación y registro' },
        { type: 'ul', items: [
          'Nombre y apellido completos.',
          'Tipo y número de documento (DNI, CUIT, CUIL, pasaporte).',
          'Fecha y lugar de nacimiento.',
          'Nacionalidad.',
          'Estado civil.',
          'Sexo o género (cuando lo provea el Usuario voluntariamente).',
          'Domicilio real, postal y/o fiscal.',
          'Dirección de correo electrónico.',
          'Número de teléfono fijo y/o celular.',
        ]},
        { type: 'h3', text: '3.2. Datos biométricos y documentales (KYC)' },
        { type: 'ul', items: [
          'Imagen del documento de identidad: fotografía clara del DNI, anverso y reverso (o documento equivalente).',
          'Imagen biométrica facial: selfie con prueba de vida ("liveness detection").',
          'Vector biométrico o template biométrico derivado del rostro, utilizado para cotejo.',
          'Resultados de la verificación contra bases de datos públicas (RENAPER, entre otras).',
          'Resultados de listas restrictivas (PEP, sanciones OFAC, ONU, UE).',
        ]},
        { type: 'h3', text: '3.3. Datos financieros y fiscales' },
        { type: 'ul', items: [
          'Condición tributaria (Responsable Inscripto, Monotributo, Exento, Consumidor Final, etc.).',
          'CUIT o CUIL.',
          'Datos bancarios: CBU, CVU, alias, número de cuenta y entidad.',
          'Datos de tarjetas de crédito o débito (tokenizados a través de procesadores de pago externos certificados PCI-DSS; LÓTUM no almacena PAN ni CVV).',
          'Direcciones de billeteras (wallets) de criptoactivos y redes blockchain utilizadas.',
          'Declaraciones sobre origen lícito de los fondos.',
          'Historial de pagos, facturas y comprobantes.',
        ]},
        { type: 'h3', text: '3.4. Datos vinculados a inmuebles y operaciones' },
        { type: 'ul', items: [
          'Datos dominiales del inmueble: dirección, matrícula, nomenclatura catastral, partida inmobiliaria, superficie, estado de ocupación.',
          'Documentación dominial: títulos de propiedad, planos, reglamento de copropiedad, informes de dominio e inhibiciones.',
          'Información sobre la operación: monto pactado, plazos, avance de obra, fotografías del inmueble.',
          'Comunicaciones entre Usuarios cursadas a través de la Plataforma.',
        ]},
        { type: 'h3', text: '3.5. Datos técnicos y de navegación' },
        { type: 'ul', items: [
          'Dirección IP.',
          'Tipo y versión de navegador, sistema operativo, modelo de dispositivo.',
          'Identificadores únicos de dispositivo (IDFA, AAID).',
          'Datos de geolocalización aproximada (a nivel de ciudad/región).',
          'Páginas visitadas, tiempo de permanencia, interacciones, clics.',
          'Datos de cookies y tecnologías similares.',
          'Registros de acceso (logs), fechas y horas de conexión.',
        ]},
        { type: 'h3', text: '3.6. Datos de soporte y comunicaciones' },
        { type: 'ul', items: [
          'Contenido de consultas, reclamos y comunicaciones con LÓTUM (email, formularios, chat).',
          'Grabaciones de llamadas, cuando correspondiere, previo aviso al Usuario.',
          'Encuestas de satisfacción y feedback.',
        ]},
        { type: 'h3', text: '3.7. Datos de terceros' },
        { type: 'p', text: 'Si el Usuario provee datos de terceros (por ejemplo, cotitulares de un inmueble, herederos, apoderados, contratistas), declara contar con autorización suficiente para hacerlo y asume frente a LÓTUM la indemnidad correspondiente.' },
      ],
    },
    {
      id: 'finalidades',
      number: '4',
      title: 'Finalidades del tratamiento',
      content: [
        { type: 'p', text: 'LÓTUM trata los datos personales con las siguientes finalidades, todas legítimas, específicas, explícitas y no incompatibles entre sí:' },
        { type: 'ul', items: [
          'Registrar y administrar la Cuenta del Usuario.',
          'Verificar la identidad del Usuario (KYC) y prevenir suplantación de identidad, fraude y estafas.',
          'Cumplir con la normativa de prevención de lavado de activos y financiamiento del terrorismo.',
          'Facilitar el matchmaking entre Propietarios e Inversores.',
          'Documentar, almacenar y gestionar Operaciones.',
          'Procesar pagos, emitir facturas y cumplir obligaciones tributarias.',
          'Brindar soporte al Usuario, atender consultas y reclamos.',
          'Comunicar novedades, cambios y avisos relevantes sobre la Plataforma.',
          'Enviar comunicaciones comerciales y publicitarias, previo consentimiento del Usuario, con opción de baja en todo momento.',
          'Realizar análisis estadísticos, métricas, mejoras del producto y desarrollo de nuevos servicios.',
          'Prevenir, detectar e investigar fraudes, abusos, ataques y violaciones de seguridad.',
          'Cumplir con obligaciones legales, requerimientos judiciales o de autoridades administrativas.',
          'Ejercer y defender derechos en sede administrativa o judicial.',
          'Evaluar el riesgo crediticio y reputacional de los Usuarios cuando corresponda.',
        ]},
      ],
    },
    {
      id: 'base-legitimacion',
      number: '5',
      title: 'Base de legitimación del tratamiento',
      content: [
        { type: 'p', text: 'LÓTUM trata los datos personales sobre las siguientes bases jurídicas:' },
        { type: 'ul', items: [
          'Consentimiento del Titular: para todas aquellas finalidades en que el consentimiento es exigido por la ley, especialmente para el tratamiento de datos biométricos y para el envío de comunicaciones comerciales.',
          'Ejecución de un contrato: el tratamiento es necesario para la prestación de los Servicios solicitados por el Usuario.',
          'Obligación legal: el tratamiento es necesario para cumplir con obligaciones que pesan sobre LÓTUM (KYC, PLA/FT, AFIP, UIF, requerimientos judiciales).',
          'Interés legítimo: para prevenir fraudes, mejorar la Plataforma, garantizar la seguridad y proteger derechos propios y de terceros, en la medida que dicho interés no sea contrario a los derechos fundamentales del Titular.',
        ]},
      ],
    },
    {
      id: 'biometricos',
      number: '6',
      title: 'Tratamiento especial de datos biométricos',
      content: [
        { type: 'p', text: 'LÓTUM otorga a los datos biométricos un tratamiento reforzado por su carácter sensible y único e irrepetible.' },
        { type: 'h3', text: '6.1. Consentimiento expreso' },
        { type: 'p', text: 'El tratamiento de datos biométricos se realiza únicamente previo consentimiento libre, expreso, previo, informado e inequívoco del Titular, prestado mediante una acción afirmativa específica (aceptación separada en la Plataforma, no por defecto).' },
        { type: 'h3', text: '6.2. Finalidad específica y limitada' },
        { type: 'p', text: 'Los datos biométricos serán utilizados exclusivamente para: (i) verificar la identidad del Usuario al momento del registro; (ii) cotejar la coincidencia con el documento de identidad; (iii) prevenir suplantación de identidad y fraude; (iv) reverificación de identidad en operaciones de alto riesgo. NO serán utilizados para perfilamiento publicitario, reconocimiento facial en espacios públicos, ni cedidos comercialmente a terceros.' },
        { type: 'h3', text: '6.3. Seguridad reforzada' },
        { type: 'p', text: 'Los datos biométricos son almacenados con cifrado fuerte (AES-256 o equivalente), bajo controles estrictos de acceso, registros de auditoría detallados y separados lógicamente del resto de los datos. Se aplican técnicas de minimización: cuando es técnicamente posible, se almacena únicamente el template biométrico (vector matemático) y no la imagen original.' },
        { type: 'h3', text: '6.4. Plazo de conservación' },
        { type: 'p', text: 'Los datos biométricos se conservarán mientras la Cuenta esté activa y por el plazo legal de archivo obligatorio aplicable (en general, DIEZ (10) años conforme la normativa PLA/FT vigente), salvo revocación del consentimiento por parte del Titular.' },
        { type: 'h3', text: '6.5. Derecho de revocación' },
        { type: 'p', text: 'El Titular podrá revocar el consentimiento al tratamiento biométrico en cualquier momento, lo que implicará la imposibilidad de seguir operando en la Plataforma. La revocación no afectará la licitud de los tratamientos realizados con anterioridad.' },
      ],
    },
    {
      id: 'destinatarios',
      number: '7',
      title: 'Destinatarios y cesión de datos',
      content: [
        { type: 'p', text: 'LÓTUM podrá compartir datos personales con los siguientes destinatarios, exclusivamente en la medida necesaria para las finalidades descriptas:' },
        { type: 'h3', text: '7.1. Proveedores y encargados del tratamiento' },
        { type: 'ul', items: [
          'Proveedores de servicios de verificación de identidad (KYC) y biometría facial.',
          'Proveedores de servicios en la nube (hosting, almacenamiento, backup).',
          'Procesadores de pagos con tarjeta, transferencias y criptoactivos.',
          'Proveedores de análisis blockchain (AML/cripto-compliance).',
          'Proveedores de envío de correos electrónicos transaccionales y campañas.',
          'Proveedores de analítica web y mobile.',
          'Estudios contables, auditores externos y asesores profesionales.',
        ]},
        { type: 'p', text: 'Todos los proveedores actúan como encargados del tratamiento, bajo contrato escrito que garantiza el cumplimiento de la Ley 25.326 y la confidencialidad de los datos.' },
        { type: 'h3', text: '7.2. Otros Usuarios de la Plataforma' },
        { type: 'p', text: 'Cierta información será visible para otros Usuarios en el marco de las Operaciones (por ejemplo, nombre, datos de contacto, datos del inmueble, etc.). El Usuario reconoce y acepta este flujo de información como inherente al funcionamiento de la Plataforma.' },
        { type: 'h3', text: '7.3. Autoridades públicas' },
        { type: 'p', text: 'LÓTUM podrá ceder datos a autoridades judiciales, administrativas, fiscales o regulatorias cuando exista un requerimiento legal válido (orden judicial, requerimiento UIF, AFIP, BCRA, CNV, AAIP, etc.).' },
        { type: 'h3', text: '7.4. Sociedades del grupo' },
        { type: 'p', text: 'LÓTUM podrá compartir datos con sociedades controlantes, controladas o vinculadas para fines administrativos y operativos internos, bajo los mismos estándares de protección.' },
        { type: 'h3', text: '7.5. Transferencias en el contexto de operaciones societarias' },
        { type: 'p', text: 'En caso de fusión, escisión, adquisición, venta de activos o reorganización societaria, los datos podrán ser transferidos al nuevo titular, garantizándose la continuidad de los niveles de protección.' },
      ],
    },
    {
      id: 'transferencia-internacional',
      number: '8',
      title: 'Transferencia internacional de datos',
      content: [
        { type: 'p', text: 'Algunos proveedores de servicios pueden encontrarse en jurisdicciones distintas a la República Argentina. LÓTUM realiza transferencias internacionales únicamente:' },
        { type: 'ul', items: [
          'A países considerados con nivel adecuado de protección por la AAIP.',
          'Mediante cláusulas contractuales tipo aprobadas o estándares contractuales equivalentes a los aprobados por la AAIP.',
          'Con el consentimiento informado del Titular cuando corresponda.',
          'En cumplimiento de obligaciones legales o defensa de derechos en sede judicial.',
        ]},
        { type: 'p', text: 'El Usuario presta su consentimiento expreso para dichas transferencias internacionales, en la medida que sean necesarias para la prestación de los Servicios.' },
      ],
    },
    {
      id: 'plazos',
      number: '9',
      title: 'Plazos de conservación',
      content: [
        { type: 'p', text: 'LÓTUM conserva los datos personales por los plazos necesarios para cumplir con las finalidades para las cuales fueron recolectados, y por los plazos legales de archivo obligatorio. A modo orientativo:' },
        { type: 'table',
          headers: ['Tipo de dato', 'Plazo de conservación'],
          rows: [
            ['Datos de registro y Cuenta', 'Mientras la Cuenta esté activa + 5 años desde la baja'],
            ['Datos KYC y biométricos', 'Mientras la Cuenta esté activa + 10 años (Ley 25.246)'],
            ['Datos fiscales y contables', '10 años (normativa AFIP y comercial)'],
            ['Comunicaciones y soporte', '3 años desde la última comunicación'],
            ['Logs y datos de navegación', '12 a 24 meses, según finalidad'],
            ['Datos vinculados a Operaciones', '10 años desde el cierre de la Operación'],
          ],
        },
        { type: 'p', text: 'Vencidos los plazos, los datos serán suprimidos, anonimizados o disociados de manera irreversible, salvo que deban conservarse por requerimiento judicial o legal específico.' },
      ],
    },
    {
      id: 'cookies',
      number: '10',
      title: 'Cookies y tecnologías similares',
      content: [
        { type: 'p', text: 'LÓTUM utiliza cookies y tecnologías similares (píxeles, web beacons, SDKs, identificadores de dispositivo) con las siguientes finalidades:' },
        { type: 'h3', text: '10.1. Tipos de cookies' },
        { type: 'ul', items: [
          'Cookies estrictamente necesarias: imprescindibles para el funcionamiento de la Plataforma (autenticación, seguridad, balanceo de carga). No requieren consentimiento.',
          'Cookies de preferencias: recuerdan elecciones del Usuario (idioma, región). Requieren consentimiento.',
          'Cookies analíticas: miden uso y rendimiento de la Plataforma. Requieren consentimiento.',
          'Cookies publicitarias y de marketing: personalizan contenido y publicidad. Requieren consentimiento expreso.',
        ]},
        { type: 'h3', text: '10.2. Gestión del consentimiento' },
        { type: 'p', text: 'Al ingresar por primera vez a la Plataforma, se presenta un panel de gestión de cookies que permite aceptar, rechazar o configurar individualmente cada categoría. El Usuario podrá modificar sus preferencias en cualquier momento desde el panel de configuración.' },
      ],
    },
    {
      id: 'derechos',
      number: '11',
      title: 'Derechos del titular de los datos',
      content: [
        { type: 'p', text: 'Conforme a la Ley 25.326, el Titular tiene los siguientes derechos respecto de sus datos personales:' },
        { type: 'h3', text: '11.1. Derecho de acceso' },
        { type: 'p', text: 'Conocer qué datos personales tiene LÓTUM, con qué finalidad y a quiénes han sido cedidos. El primer acceso es gratuito y puede ejercerse cada SEIS (6) meses, salvo interés legítimo acreditado.' },
        { type: 'h3', text: '11.2. Derecho de rectificación, actualización y supresión' },
        { type: 'p', text: 'Solicitar la corrección de datos inexactos o desactualizados, así como la supresión de aquellos cuyo tratamiento no se ajuste a la ley o cuando hayan dejado de ser necesarios.' },
        { type: 'h3', text: '11.3. Derecho de oposición' },
        { type: 'p', text: 'Oponerse al tratamiento de datos para finalidades específicas, especialmente publicidad y comunicaciones comerciales.' },
        { type: 'h3', text: '11.4. Derecho a la portabilidad' },
        { type: 'p', text: 'Recibir los datos en un formato estructurado, de uso común y lectura mecánica, o solicitar su transmisión a otro responsable cuando sea técnicamente posible.' },
        { type: 'h3', text: '11.5. Derecho a no ser objeto de decisiones automatizadas' },
        { type: 'p', text: 'Solicitar la revisión humana de decisiones que se basen exclusivamente en tratamiento automatizado y que produzcan efectos jurídicos significativos.' },
        { type: 'h3', text: '11.6. Ejercicio de los derechos' },
        { type: 'p', text: 'Para ejercer estos derechos, el Titular podrá:' },
        { type: 'ul', items: [
          'Enviar un correo electrónico a contacto@lotum.com.ar con su solicitud, acompañando copia del documento de identidad.',
          'Utilizar el formulario disponible en la Plataforma.',
          'Dirigirse por escrito al domicilio legal de LÓTUM.',
        ]},
        { type: 'p', text: 'LÓTUM responderá dentro de los DIEZ (10) días corridos en el caso de acceso, y dentro de los CINCO (5) días corridos en los casos de rectificación, actualización o supresión, conforme la Ley 25.326.' },
        { type: 'h3', text: '11.7. Reclamo ante la autoridad de control' },
        { type: 'p', text: 'El Titular podrá presentar reclamos o denuncias ante la Agencia de Acceso a la Información Pública (AAIP), domiciliada en Av. Pte. Gral. Julio A. Roca 710, Piso 2, Ciudad Autónoma de Buenos Aires, o a través del sitio web argentina.gob.ar/aaip.' },
      ],
    },
    {
      id: 'seguridad',
      number: '12',
      title: 'Medidas de seguridad',
      content: [
        { type: 'p', text: 'LÓTUM aplica medidas técnicas, físicas y organizativas razonables y conformes al estado de la técnica para proteger los datos personales contra accesos no autorizados, pérdida, alteración o destrucción, incluyendo:' },
        { type: 'ul', items: [
          'Cifrado en tránsito (TLS 1.2 o superior) y en reposo (AES-256 o equivalente).',
          'Control de accesos basado en roles (RBAC) y principio de mínimo privilegio.',
          'Autenticación multifactor (MFA) para accesos a sistemas internos.',
          'Registros de auditoría y monitoreo continuo.',
          'Pruebas periódicas de seguridad (pentesting, vulnerability scanning).',
          'Backups regulares y planes de continuidad de negocio.',
          'Capacitación periódica del personal.',
          'Acuerdos de confidencialidad con empleados y proveedores.',
        ]},
        { type: 'p', text: 'Sin perjuicio de lo anterior, el Usuario reconoce que ningún sistema es absolutamente inviolable. LÓTUM no garantiza la inexistencia absoluta de incidentes, pero se compromete a actuar con la debida diligencia.' },
      ],
    },
    {
      id: 'incidentes',
      number: '13',
      title: 'Notificación de incidentes de seguridad',
      content: [
        { type: 'p', text: 'En caso de detectarse un incidente de seguridad que afecte datos personales y que pueda implicar riesgo significativo para los derechos de los Titulares, LÓTUM notificará dicho evento a la AAIP y a los Titulares afectados, conforme a los plazos y procedimientos establecidos en la normativa aplicable, indicando: naturaleza del incidente, categorías de datos comprometidos, medidas adoptadas y recomendaciones.' },
      ],
    },
    {
      id: 'menores',
      number: '14',
      title: 'Menores de edad',
      content: [
        { type: 'p', text: 'La Plataforma está destinada exclusivamente a personas mayores de DIECIOCHO (18) años. LÓTUM no recolecta intencionadamente datos de menores. En caso de detectarse el registro de un menor, la Cuenta será dada de baja inmediatamente y los datos serán eliminados, salvo deber legal de conservación.' },
      ],
    },
    {
      id: 'marketing',
      number: '15',
      title: 'Comunicaciones comerciales y marketing',
      content: [
        { type: 'p', text: 'LÓTUM podrá enviar comunicaciones comerciales, newsletters, promociones y novedades, únicamente a los Usuarios que hayan prestado consentimiento expreso. El Usuario podrá oponerse en cualquier momento mediante el enlace de baja incluido en cada comunicación o a través del panel de preferencias de su Cuenta.' },
        { type: 'p', text: 'LÓTUM respeta los registros "No Llame" (Ley 26.951) y "No Enviar" en los términos previstos por la normativa vigente.' },
      ],
    },
    {
      id: 'perfiles',
      number: '16',
      title: 'Perfiles y decisiones automatizadas',
      content: [
        { type: 'p', text: 'LÓTUM puede utilizar herramientas automatizadas, incluyendo modelos de inteligencia artificial y aprendizaje automático, para finalidades tales como: detección de fraude, scoring de riesgo, recomendaciones personalizadas y análisis de comportamiento.' },
        { type: 'p', text: 'Las decisiones automatizadas que produzcan efectos jurídicos significativos (por ejemplo, rechazo de KYC, bloqueo de Cuenta por sospecha de fraude) podrán ser revisadas por intervención humana ante solicitud del Titular.' },
      ],
    },
    {
      id: 'enlaces-terceros',
      number: '17',
      title: 'Enlaces a sitios de terceros',
      content: [
        { type: 'p', text: 'La Plataforma puede contener enlaces a sitios web o aplicaciones de terceros. LÓTUM no se responsabiliza por las políticas de privacidad ni el tratamiento de datos realizado por esos terceros. Se recomienda al Usuario revisar las políticas de cada sitio antes de proporcionar datos personales.' },
      ],
    },
    {
      id: 'modificaciones',
      number: '18',
      title: 'Modificaciones a la política',
      content: [
        { type: 'p', text: 'LÓTUM podrá modificar la presente Política cuando lo estime conveniente o cuando lo exija una modificación normativa. Las modificaciones se notificarán a través de la Plataforma y/o por correo electrónico con un preaviso mínimo de DIEZ (10) días corridos antes de su entrada en vigencia, salvo cuando deban tener efecto inmediato por imperativo legal. La continuación en el uso de la Plataforma implica la aceptación de la versión vigente.' },
      ],
    },
    {
      id: 'contacto',
      number: '19',
      title: 'Contacto y oficial de protección de datos',
      content: [
        { type: 'p', text: 'Para toda consulta, reclamo o ejercicio de derechos relacionados con la presente Política, el Titular podrá contactarse con:' },
        { type: 'ul', items: [
          'Correo electrónico general de privacidad: contacto@lotum.com.ar',
          'WhatsApp: +54 9 223 583 4453',
          'Formulario disponible en la Plataforma.',
          'Domicilio postal: Mar del Plata, Provincia de Buenos Aires.',
          'Autoridad de control: Agencia de Acceso a la Información Pública (AAIP) — argentina.gob.ar/aaip',
        ]},
      ],
    },
  ],
  closingBox: {
    title: 'Aceptación expresa',
    text: 'AL HACER CLIC EN "ACEPTO", AL CREAR UNA CUENTA O AL UTILIZAR LA PLATAFORMA, EL USUARIO MANIFIESTA HABER LEÍDO, COMPRENDIDO Y ACEPTADO LA PRESENTE POLÍTICA DE PRIVACIDAD, PRESTANDO CONSENTIMIENTO LIBRE, EXPRESO, PREVIO E INFORMADO AL TRATAMIENTO DE SUS DATOS PERSONALES, INCLUIDOS LOS DATOS BIOMÉTRICOS, EN LOS TÉRMINOS AQUÍ DESCRIPTOS Y CONFORME A LA LEY 25.326.',
  },
};

export default PRIVACIDAD_DATA;
