// =======================================================================
//   LÓTUM — POLÍTICA DE PUBLICIDAD (datos)
// =======================================================================
const PUBLICIDAD_DATA = {
  meta: {
    version: 'Versión 1.0',
    note: 'Documento de trabajo para revisión legal',
    updatedAt: '27 de noviembre de 2026',
    jurisdiction: 'Decreto-Ley 274/2019 — Argentina',
  },
  preamble: `La presente Política de Publicidad y Contenido Promocional (en adelante, la "Política") establece los principios, reglas y obligaciones aplicables a toda actividad publicitaria, promocional, de marketing y comunicación comercial vinculada a la plataforma digital LÓTUM (en adelante, la "Plataforma"), tanto la desarrollada directamente por LÓTUM como la realizada por Usuarios, anunciantes, corredores inmobiliarios, influencers, embajadores de marca, afiliados y cualquier tercero que colabore en la promoción de los Servicios.

La presente Política aplica a la publicidad institucional de LÓTUM, publicaciones de inmuebles cargadas por Usuarios, contenido patrocinado, campañas en redes sociales, motores de búsqueda, email marketing, mensajería instantánea, campañas con influencers y afiliados, comunicaciones promocionales a Usuarios registrados, y cualquier otro contenido con finalidad publicitaria.

El cumplimiento de esta Política es OBLIGATORIO para todo Usuario que publique contenido en la Plataforma y para todo tercero que celebre acuerdos publicitarios con LÓTUM.`,
  preambleTitle: 'Objeto y alcance',
  sections: [
    {
      id: 'marco-legal',
      number: '1',
      title: 'Marco legal aplicable',
      content: [
        { type: 'p', text: 'La presente Política se rige por la normativa aplicable a la publicidad, lealtad comercial y defensa del consumidor vigente en la República Argentina, incluyendo de manera enunciativa y no limitativa:' },
        { type: 'ul', items: [
          'Artículo 42 de la Constitución Nacional.',
          'Ley N° 24.240 de Defensa del Consumidor y modificatorias.',
          'Decreto-Ley N° 274/2019 de Lealtad Comercial (que reemplazó a la Ley 22.802).',
          'Resolución N° 915/2017 de la Secretaría de Comercio (publicidad inmobiliaria).',
          'Código Civil y Comercial de la Nación (contratos de consumo).',
          'Ley N° 25.156 de Defensa de la Competencia.',
          'Ley N° 22.362 de Marcas y Designaciones.',
          'Ley N° 11.723 de Propiedad Intelectual.',
          'Ley N° 25.326 de Protección de Datos Personales.',
          'Ley N° 26.522 de Servicios de Comunicación Audiovisual (cuando aplique).',
          'Ley N° 26.485 de Protección Integral a las Mujeres (publicidad no estereotipada).',
          'Ley N° 26.061 de Protección Integral de los Derechos de Niñas, Niños y Adolescentes.',
          'Ley N° 23.592 contra Actos Discriminatorios.',
          'Ley N° 25.246 de Prevención del Lavado de Activos y normativa UIF.',
          'Resolución General CNV N° 994/2024 (PSAV) y normativa BCRA aplicable a la promoción de productos vinculados a criptoactivos.',
          'Ley N° 25.065 de Tarjetas de Crédito (en lo aplicable a publicidad financiera).',
          'Código de Ética del Consejo de Autorregulación Publicitaria (CONARP), adoptado a título de buena práctica.',
          'Normativa de la Federación Argentina de Inmobiliarias (FAIR) y de los Colegios Profesionales de Corredores Inmobiliarios en cada jurisdicción.',
        ]},
      ],
    },
    {
      id: 'definiciones',
      number: '2',
      title: 'Definiciones',
      content: [
        { type: 'definitions', items: [
          ['Publicidad', 'toda forma de comunicación realizada con el fin de promover, directa o indirectamente, la contratación de los Servicios de LÓTUM, la venta de inmuebles, oportunidades de inversión o cualquier otro producto o servicio asociado.'],
          ['Anunciante', 'cualquier persona humana o jurídica que contrate espacios publicitarios, posiciones destacadas o servicios promocionales dentro de la Plataforma.'],
          ['Publicación de Inmueble', 'ficha, listado o aviso cargado por un Usuario en la Plataforma con datos, fotografías y características de un inmueble destinado a la inversión, reciclado y/o venta.'],
          ['Influencer o Embajador de Marca', 'persona humana con audiencia en redes sociales contratada por LÓTUM, mediante acuerdo escrito o canje, para promocionar la Plataforma.'],
          ['Afiliado', 'tercero que promociona los Servicios de LÓTUM a cambio de una comisión por resultado (registros, contrataciones, ventas).'],
          ['Contenido Patrocinado', 'contenido cuya difusión ha sido pagada o compensada por LÓTUM o un Anunciante.'],
          ['Listado Destacado', 'publicación de inmueble que ocupa una posición preferencial en los resultados de búsqueda mediante un pago adicional.'],
          ['Cookies Publicitarias', 'tecnologías de seguimiento utilizadas para personalizar publicidad y medir su rendimiento.'],
        ]},
      ],
    },
    {
      id: 'principios',
      number: '3',
      title: 'Principios generales de la publicidad en Lótum',
      content: [
        { type: 'p', text: 'Toda publicidad difundida en o a través de LÓTUM deberá ajustarse a los siguientes principios rectores:' },
        { type: 'h3', text: '3.1. Veracidad' },
        { type: 'p', text: 'La publicidad debe ser veraz, exacta y verificable. Toda afirmación sobre características, precios, ubicación, superficie, estado, antigüedad, servicios, infraestructura, rentabilidad estimada o cualquier dato relevante del inmueble o de los Servicios debe corresponderse fielmente con la realidad y poder ser acreditada documentalmente.' },
        { type: 'h3', text: '3.2. Claridad' },
        { type: 'p', text: 'Los mensajes publicitarios deben ser claros, comprensibles y no inducir a confusión, equívocos o falsas expectativas. Toda condición esencial debe estar destacada y no oculta en letra pequeña o referencias ilegibles.' },
        { type: 'h3', text: '3.3. Identificación' },
        { type: 'p', text: 'Toda publicidad debe ser claramente identificable como tal. El Contenido Patrocinado, los Listados Destacados y los anuncios pagos deberán estar señalizados de forma visible mediante etiquetas como "Publicidad", "Patrocinado", "Anuncio", "Destacado" o equivalentes, evitando cualquier práctica de publicidad encubierta.' },
        { type: 'h3', text: '3.4. Lealtad comercial' },
        { type: 'p', text: 'La publicidad no podrá denigrar, menospreciar ni hacer comparaciones engañosas, falsas o injustificadas con competidores, ni aprovecharse indebidamente del prestigio de marcas, nombres comerciales o signos distintivos ajenos.' },
        { type: 'h3', text: '3.5. Respeto por la dignidad humana' },
        { type: 'p', text: 'La publicidad deberá respetar la dignidad de las personas, evitar contenidos discriminatorios por razón de género, raza, religión, orientación sexual, edad, nacionalidad, discapacidad o condición social, y no podrá utilizar estereotipos sexistas o violentos.' },
        { type: 'h3', text: '3.6. Protección de menores' },
        { type: 'p', text: 'Queda prohibida la publicidad dirigida a menores de DIECIOCHO (18) años, así como la utilización de imágenes de menores sin consentimiento escrito de sus padres o representantes legales y con resguardo de su intimidad.' },
        { type: 'h3', text: '3.7. Protección del consumidor' },
        { type: 'p', text: 'La publicidad obliga a LÓTUM y/o al Anunciante en los términos del artículo 7° y 8° de la Ley 24.240: los términos de la oferta integran el contrato celebrado con el consumidor.' },
      ],
    },
    {
      id: 'publicidad-institucional',
      number: '4',
      title: 'Publicidad institucional y de marca de Lótum',
      content: [
        { type: 'h3', text: '4.1. Mensajes institucionales' },
        { type: 'p', text: 'LÓTUM realizará publicidad de su marca, sus Servicios y su propuesta de valor a través de medios digitales, gráficos, audiovisuales, redes sociales y vía pública, conforme a los principios de la presente Política.' },
        { type: 'h3', text: '4.2. Promesas y proyecciones' },
        { type: 'p', text: 'LÓTUM se abstendrá de garantizar resultados económicos, rentabilidades, plusvalías, plazos de venta u otras variables que dependan de factores externos. Cualquier referencia a desempeño histórico, casos de éxito o proyecciones llevará una aclaración expresa de que:' },
        { type: 'ul', items: [
          'Los resultados pasados no garantizan resultados futuros.',
          'Las proyecciones son estimaciones y no constituyen asesoramiento financiero ni promesa de rentabilidad.',
          'Toda inversión inmobiliaria conlleva riesgos que deben evaluarse con asesoramiento profesional independiente.',
        ]},
        { type: 'h3', text: '4.3. Publicidad sobre criptoactivos' },
        { type: 'p', text: 'Cuando la publicidad refiera a la aceptación de criptoactivos como medio de pago u operatoria asociada, LÓTUM incluirá disclaimers que adviertan: (i) que los criptoactivos no son moneda de curso legal en la República Argentina; (ii) que su valor es volátil; (iii) que las operaciones con criptoactivos son irreversibles; (iv) que el Usuario debe informarse adecuadamente antes de operar.' },
        { type: 'h3', text: '4.4. Testimoniales y casos de éxito' },
        { type: 'p', text: 'Toda publicación de testimoniales, reseñas o casos de éxito requerirá: (i) consentimiento escrito del testimoniante; (ii) veracidad del testimonio; (iii) representatividad del resultado (cuando se trate de un caso excepcional, deberá aclararse expresamente); (iv) cumplimiento de la Ley 25.326 en cuanto al uso de imagen y datos personales.' },
      ],
    },
    {
      id: 'publicaciones-inmuebles',
      number: '5',
      title: 'Publicaciones de inmuebles cargadas por usuarios',
      content: [
        { type: 'p', text: 'Los Usuarios que carguen publicaciones de inmuebles en la Plataforma se comprometen a cumplir las siguientes reglas, en consonancia con la Resolución 915/2017 SC:' },
        { type: 'h3', text: '5.1. Información mínima obligatoria' },
        { type: 'p', text: 'Toda publicación de inmueble deberá incluir, como mínimo:' },
        { type: 'ul', items: [
          'Dirección del inmueble (al menos ciudad/localidad y barrio; la dirección exacta podrá reservarse hasta la etapa de contacto).',
          'Tipo de inmueble (departamento, casa, terreno, local, etc.).',
          'Superficie cubierta, semicubierta y total.',
          'Cantidad de ambientes, dormitorios y baños.',
          'Antigüedad o año de construcción aproximado.',
          'Estado de conservación y mejoras recientes.',
          'Precio expresado en pesos argentinos (ARS) o en dólares estadounidenses (USD), claramente identificado.',
          'Identificación del responsable de la publicación: si es titular, si actúa como corredor inmobiliario matriculado (con número de matrícula), o si es Inversor.',
          'Condición fiscal y/o expensas aplicables, cuando corresponda.',
        ]},
        { type: 'h3', text: '5.2. Veracidad de las fotografías' },
        { type: 'p', text: 'Las fotografías deben corresponder al inmueble efectivamente publicado, ser actuales (no superiores a SEIS (6) meses) y reflejar fielmente su estado. Está prohibido el uso de imágenes de inmuebles distintos, retoques engañosos que oculten defectos, o renders no identificados como tales.' },
        { type: 'p', text: 'Los renders, ilustraciones o imágenes generadas por inteligencia artificial deberán identificarse expresamente con la leyenda "Imagen ilustrativa", "Render" o "Imagen generada por IA", según corresponda.' },
        { type: 'h3', text: '5.3. Corredores inmobiliarios matriculados' },
        { type: 'p', text: 'Las publicaciones realizadas por corredores inmobiliarios deberán incluir el número de matrícula profesional, el colegio o consejo de matriculación correspondiente y la jurisdicción, conforme a la Ley 25.028 y a la normativa provincial aplicable.' },
        { type: 'p', text: 'LÓTUM podrá requerir a quienes se identifiquen como corredores la acreditación documental de su matrícula vigente, y dar de baja publicaciones de personas no matriculadas que ejerzan corretaje sin habilitación legal.' },
        { type: 'h3', text: '5.4. Precios y monedas' },
        { type: 'p', text: 'El precio publicado debe ser claro y final. Si admite ajustes (negociable, financiación, descuentos por pago al contado, etc.) deberá indicarse de forma expresa. Cuando se publique en moneda extranjera o criptoactivos, se indicará el tipo de cambio o cotización de referencia y la fecha.' },
        { type: 'h3', text: '5.5. Prohibiciones específicas para publicaciones' },
        { type: 'ul', items: [
          'Publicar inmuebles sobre los que no se tenga titularidad ni autorización del titular.',
          'Cargar precios irreales, ficticios o intencionalmente engañosos.',
          'Duplicar publicaciones para inflar artificialmente la oferta o el posicionamiento.',
          'Ocultar gravámenes, embargos, ocupantes, vicios redhibitorios u otros aspectos que afecten la operación.',
          'Discriminar a potenciales interesados por motivos de género, raza, religión, orientación sexual, nacionalidad, condición social, discapacidad, presencia de niños o mascotas (sin perjuicio de las normas de copropiedad aplicables).',
          'Publicar inmuebles con destino contrario a la ley (actividades ilícitas).',
        ]},
      ],
    },
    {
      id: 'contenido-patrocinado',
      number: '6',
      title: 'Contenido patrocinado y listados destacados',
      content: [
        { type: 'h3', text: '6.1. Definición y modalidades' },
        { type: 'p', text: 'LÓTUM ofrece a Usuarios y Anunciantes la posibilidad de contratar:' },
        { type: 'ul', items: [
          'Listados Destacados: publicaciones de inmuebles con posicionamiento preferencial.',
          'Banners y anuncios display dentro de la Plataforma.',
          'Contenido patrocinado en newsletters, notificaciones push o redes sociales asociadas a LÓTUM.',
          'Promociones cruzadas con marcas o proveedores.',
        ]},
        { type: 'h3', text: '6.2. Identificación obligatoria' },
        { type: 'p', text: 'Todo Contenido Patrocinado y Listado Destacado estará claramente identificado mediante etiquetas visibles tales como "Publicidad", "Patrocinado", "Destacado" o "Anuncio", conforme al estándar de la industria y a la normativa de lealtad comercial.' },
        { type: 'h3', text: '6.3. Revisión previa' },
        { type: 'p', text: 'LÓTUM se reserva el derecho de revisar, aprobar, rechazar, modificar o retirar cualquier Contenido Patrocinado que: (i) infrinja la presente Política; (ii) contravenga normativa vigente; (iii) genere riesgo reputacional o legal; (iv) sea contrario a los intereses de los Usuarios o de la Plataforma. Esta facultad se ejerce sin que ello genere derecho a indemnización alguna a favor del Anunciante, más allá del eventual reembolso proporcional del valor abonado.' },
        { type: 'h3', text: '6.4. Responsabilidad del Anunciante' },
        { type: 'p', text: 'El Anunciante es responsable por la veracidad, legalidad y exactitud del contenido publicitario provisto, así como por contar con todas las autorizaciones, licencias y derechos necesarios (marcas, imagen, propiedad intelectual, etc.). El Anunciante se obliga a mantener indemne a LÓTUM frente a cualquier reclamo de terceros derivado de su publicidad.' },
      ],
    },
    {
      id: 'redes-sociales',
      number: '7',
      title: 'Publicidad en redes sociales y canales externos',
      content: [
        { type: 'p', text: 'LÓTUM desarrolla campañas en redes sociales (Instagram, Facebook, TikTok, LinkedIn, X, YouTube, etc.), motores de búsqueda (Google Ads, Bing Ads), aplicaciones de mensajería (WhatsApp Business, Telegram) y otros canales digitales, sujeto a:' },
        { type: 'ul', items: [
          'Cumplimiento de las políticas publicitarias específicas de cada plataforma.',
          'Cumplimiento de la presente Política y de la normativa argentina aplicable.',
          'Segmentación responsable: no se utilizarán criterios de segmentación discriminatorios prohibidos por ley.',
          'Adecuada gestión del consentimiento del Usuario para tratamiento de datos con fines publicitarios (cookies, píxeles, audiencias personalizadas).',
          'Respeto del Registro "No Llame" (Ley 26.951) y de los mecanismos de opt-out en email marketing y mensajería.',
        ]},
      ],
    },
    {
      id: 'influencers',
      number: '8',
      title: 'Influencer marketing y embajadores de marca',
      content: [
        { type: 'h3', text: '8.1. Contrato escrito obligatorio' },
        { type: 'p', text: 'Toda colaboración con influencers, embajadores de marca o creadores de contenido se instrumentará mediante contrato escrito que regule: alcance de la prestación, contraprestación (monetaria o en especie), entregables, tono y mensajes, derechos de uso de la imagen y del contenido, plazo, exclusividad (si la hubiera) y cláusulas de confidencialidad y no competencia.' },
        { type: 'h3', text: '8.2. Divulgación obligatoria' },
        { type: 'p', text: 'Los influencers y embajadores deberán identificar de forma clara, prominente y comprensible la naturaleza comercial del contenido mediante etiquetas como "#Publicidad", "#Ad", "#Sponsored", "En colaboración con LÓTUM", "Contenido patrocinado por LÓTUM" o equivalentes, conforme a las recomendaciones internacionales (FTC, ASA) adoptadas como buenas prácticas en Argentina.' },
        { type: 'p', text: 'La omisión o disimulo de la naturaleza comercial constituye publicidad encubierta y está expresamente prohibida.' },
        { type: 'h3', text: '8.3. Veracidad y experiencia personal' },
        { type: 'p', text: 'Los influencers no podrán afirmar haber utilizado los Servicios o experimentado resultados que no sean ciertos. Toda recomendación deberá basarse en experiencia real y verificable.' },
        { type: 'h3', text: '8.4. Conductas prohibidas' },
        { type: 'ul', items: [
          'Garantizar rentabilidades, ganancias, plusvalías o resultados económicos específicos.',
          'Recomendar inversión sin advertir sobre los riesgos.',
          'Realizar comparaciones engañosas con competidores.',
          'Utilizar contenido protegido por derechos de terceros sin autorización.',
          'Promover actividades ilícitas, juego patológico, consumos problemáticos u otros riesgos.',
        ]},
      ],
    },
    {
      id: 'afiliados',
      number: '9',
      title: 'Programa de afiliados y referidos',
      content: [
        { type: 'h3', text: '9.1. Características' },
        { type: 'p', text: 'LÓTUM podrá ofrecer un programa de afiliados y/o referidos por el cual reconocerá comisiones, créditos o beneficios a quienes promuevan los Servicios de la Plataforma y generen nuevos registros, contrataciones u Operaciones, conforme a las condiciones que se establezcan en cada momento.' },
        { type: 'h3', text: '9.2. Reglas de conducta para afiliados' },
        { type: 'ul', items: [
          'Respetar la presente Política y la normativa publicitaria aplicable.',
          'No utilizar prácticas de spam, click fraud, redirecciones engañosas, cookie stuffing ni cualquier otra práctica fraudulenta.',
          'No prometer beneficios, características o servicios distintos de los realmente ofrecidos por LÓTUM.',
          'No utilizar las marcas, logos o nombre comercial de LÓTUM más allá del uso autorizado en los materiales provistos.',
          'No realizar campañas publicitarias pagas usando palabras clave que incluyan la marca "LÓTUM" salvo autorización expresa.',
        ]},
        { type: 'h3', text: '9.3. Suspensión y baja de afiliados' },
        { type: 'p', text: 'LÓTUM podrá suspender o dar de baja cualquier afiliado que incumpla estas reglas, sin perjuicio de exigir la devolución de comisiones obtenidas de manera fraudulenta y de iniciar las acciones legales correspondientes.' },
      ],
    },
    {
      id: 'email-marketing',
      number: '10',
      title: 'Email marketing, notificaciones y mensajería',
      content: [
        { type: 'h3', text: '10.1. Consentimiento previo' },
        { type: 'p', text: 'LÓTUM enviará comunicaciones comerciales únicamente a Usuarios que hayan prestado consentimiento expreso (opt-in). Las comunicaciones transaccionales (confirmaciones, recordatorios contractuales, avisos de seguridad) no requieren consentimiento adicional.' },
        { type: 'h3', text: '10.2. Identificación clara' },
        { type: 'p', text: 'Cada comunicación comercial deberá: (i) identificar a LÓTUM como remitente; (ii) indicar su carácter publicitario; (iii) incluir un enlace o mecanismo gratuito y simple para darse de baja (opt-out); (iv) cumplir con la Ley 25.326 y la Ley 26.951.' },
        { type: 'h3', text: '10.3. Mensajería instantánea' },
        { type: 'p', text: 'El uso de canales como WhatsApp Business, SMS o notificaciones push se realizará con consentimiento del Usuario y respetando las políticas de las plataformas correspondientes y las normas locales sobre mensajería comercial no solicitada.' },
      ],
    },
    {
      id: 'cookies',
      number: '11',
      title: 'Cookies publicitarias y publicidad comportamental',
      content: [
        { type: 'p', text: 'LÓTUM utiliza cookies publicitarias, píxeles de seguimiento y tecnologías similares para personalizar la publicidad, medir la efectividad de las campañas y desarrollar audiencias. El uso de estas tecnologías se realiza:' },
        { type: 'ul', items: [
          'Con el consentimiento previo del Usuario, gestionado a través del panel de cookies de la Plataforma.',
          'Conforme a la Política de Privacidad y a la Ley 25.326.',
          'Permitiendo al Usuario revocar el consentimiento en cualquier momento.',
          'Sin utilizar datos sensibles para segmentación publicitaria.',
        ]},
        { type: 'p', text: 'LÓTUM no realizará perfilamiento publicitario con base en datos biométricos ni cederá tales datos para fines publicitarios bajo ninguna circunstancia.' },
      ],
    },
    {
      id: 'prohibiciones',
      number: '12',
      title: 'Prohibiciones generales',
      content: [
        { type: 'p', text: 'Queda expresamente prohibida toda publicidad que:' },
        { type: 'ul', items: [
          'Sea falsa, engañosa, exagerada o tendenciosa.',
          'Constituya publicidad comparativa desleal.',
          'Atente contra la dignidad de las personas o promueva discriminación.',
          'Utilice elementos o mensajes que generen miedo, alarma o aprovechamiento de situaciones de vulnerabilidad.',
          'Esté dirigida a menores de edad o utilice indebidamente su imagen.',
          'Promueva juegos de azar, apuestas o actividades nocivas.',
          'Promueva el consumo de alcohol, tabaco, sustancias prohibidas o actividades ilícitas.',
          'Incluya contenido pornográfico, violento, gore o de naturaleza sensible inadecuada.',
          'Vulnere derechos de propiedad intelectual o industrial de terceros (marcas, obras protegidas, software, etc.).',
          'Utilice testimoniales falsos o atribuidos a personas inexistentes.',
          'Realice promesas de rentabilidad garantizada en inversiones inmobiliarias o criptoactivos.',
          'Configure esquemas piramidales, ponzi o de captación irregular del ahorro público.',
          'Configure actos de competencia desleal en los términos del Decreto-Ley 274/2019.',
          'Imite o se aproveche del prestigio de marcas o signos distintivos de terceros.',
          'Utilice imágenes de personas sin su consentimiento (Ley 11.723, art. 31).',
          'Vincule la marca LÓTUM con actividades, productos o mensajes contrarios a sus valores.',
        ]},
      ],
    },
    {
      id: 'propiedad-intelectual',
      number: '13',
      title: 'Propiedad intelectual en publicidad',
      content: [
        { type: 'h3', text: '13.1. Marca LÓTUM' },
        { type: 'p', text: 'La marca "LÓTUM", su logotipo, isologotipo, paleta de colores, tipografías oficiales, voz de marca y demás elementos identitarios son propiedad exclusiva de LÓTUM. Su uso por terceros requiere autorización expresa y por escrito y debe ajustarse al Manual de Identidad Visual y de Marca.' },
        { type: 'h3', text: '13.2. Contenido provisto por Anunciantes y Usuarios' },
        { type: 'p', text: 'El Anunciante o Usuario garantiza que cuenta con todos los derechos necesarios sobre el contenido publicitario provisto (imágenes, videos, textos, música, marcas de terceros) y otorga a LÓTUM una licencia no exclusiva, gratuita, mundial y por el plazo de duración de la campaña (o de la publicación, en el caso de inmuebles) para utilizar dicho contenido con fines de prestación de los Servicios.' },
        { type: 'h3', text: '13.3. Uso de obras de terceros' },
        { type: 'p', text: 'La utilización de música, imágenes, videos, tipografías, ilustraciones o cualquier obra protegida por derechos de autor o derechos conexos en campañas publicitarias requerirá la previa licencia correspondiente (SADAIC, AADI-CAPIF, bancos de imágenes, etc.). LÓTUM no se responsabiliza por usos no autorizados realizados por Anunciantes, Usuarios o influencers.' },
      ],
    },
    {
      id: 'promociones',
      number: '14',
      title: 'Promociones, sorteos y concursos',
      content: [
        { type: 'p', text: 'Toda promoción, sorteo, concurso o acción promocional organizada por LÓTUM se regirá por bases y condiciones específicas, publicadas con antelación, que detallarán al menos:' },
        { type: 'ul', items: [
          'Organizador, vigencia y ámbito territorial.',
          'Mecánica de participación y de elección del/los ganadores.',
          'Premios, sustituciones e impuestos a cargo del ganador.',
          'Requisitos de participación y exclusiones (empleados, familiares, etc.).',
          'Tratamiento de datos personales y consentimiento para uso publicitario del ganador.',
          'Resolución de controversias y autoridad de control.',
        ]},
        { type: 'p', text: 'LÓTUM gestionará las autorizaciones correspondientes ante autoridades de juego y/o defensa del consumidor de cada jurisdicción cuando la naturaleza de la promoción lo requiera.' },
      ],
    },
    {
      id: 'revision-interna',
      number: '15',
      title: 'Proceso de revisión interna de la publicidad',
      content: [
        { type: 'p', text: 'LÓTUM ha implementado un proceso interno de revisión publicitaria que comprende:' },
        { type: 'ul', items: [
          'Revisión legal de toda campaña de marca antes de su lanzamiento.',
          'Revisión automatizada y manual de las publicaciones de inmuebles cargadas por Usuarios, mediante moderación con apoyo de inteligencia artificial.',
          'Auditoría periódica del contenido patrocinado vigente.',
          'Capacitación periódica de los equipos de marketing y atención al cliente.',
          'Registro y archivo de las piezas publicitarias por el plazo legal correspondiente.',
        ]},
      ],
    },
    {
      id: 'moderacion',
      number: '16',
      title: 'Moderación y retirada de contenidos',
      content: [
        { type: 'h3', text: '16.1. Facultades de LÓTUM' },
        { type: 'p', text: 'LÓTUM podrá moderar, editar, ocultar, suspender o retirar cualquier contenido publicitario o publicación que incumpla la presente Política, la normativa aplicable o que afecte la calidad del servicio, la seguridad de los Usuarios o la reputación de la Plataforma, sin previo aviso y sin que ello genere derecho a indemnización.' },
        { type: 'h3', text: '16.2. Mecanismo de denuncia' },
        { type: 'p', text: 'Los Usuarios y terceros podrán reportar publicaciones, anuncios o contenidos presuntamente infractores mediante el formulario de denuncia disponible en la Plataforma, indicando: (i) URL o identificación del contenido; (ii) motivo del reporte; (iii) elementos probatorios cuando estén disponibles. LÓTUM analizará los reportes con diligencia y dentro de plazos razonables.' },
        { type: 'h3', text: '16.3. Procedimiento de notice and takedown' },
        { type: 'p', text: 'Frente a denuncias fundadas sobre violaciones a derechos de terceros (propiedad intelectual, imagen, honor, etc.), LÓTUM aplicará un procedimiento de notice and takedown, contemplando: (i) revisión preliminar; (ii) eventual notificación al Usuario denunciado; (iii) retiro provisorio cuando exista verosimilitud; (iv) restitución si el Usuario acredita la legitimidad de su contenido.' },
      ],
    },
    {
      id: 'sanciones',
      number: '17',
      title: 'Sanciones por infracción a la política',
      content: [
        { type: 'p', text: 'Las infracciones a la presente Política podrán dar lugar, a criterio de LÓTUM y conforme a la gravedad, a las siguientes medidas:' },
        { type: 'table',
          headers: ['Medida', 'Supuesto típico'],
          rows: [
            ['Advertencia', 'Infracciones leves o de primera vez (formato, omisión de datos, etiquetas faltantes).'],
            ['Edición o retiro del contenido', 'Publicaciones con datos inexactos, imágenes inadecuadas o falta de información obligatoria.'],
            ['Suspensión temporaria de la Cuenta', 'Reincidencia, publicaciones engañosas, omisión de etiquetas de patrocinio.'],
            ['Baja definitiva', 'Fraude publicitario, publicación de inmuebles inexistentes o ajenos, esquemas piramidales.'],
            ['Reclamo de daños y perjuicios', 'Cuando la infracción haya generado un perjuicio concreto a LÓTUM, a otros Usuarios o a terceros.'],
            ['Denuncia ante autoridades', 'Cuando la conducta configure infracción administrativa o delito.'],
          ],
        },
      ],
    },
    {
      id: 'indemnidad',
      number: '18',
      title: 'Indemnidad',
      content: [
        { type: 'p', text: 'Los Anunciantes, Usuarios, influencers, embajadores, afiliados y demás terceros que difundan contenido publicitario vinculado a LÓTUM se obligan a mantener indemne a LÓTUM, sus accionistas, directores, empleados y proveedores, frente a cualquier reclamo, demanda, sanción administrativa, multa, condena judicial o pérdida derivada de la infracción a la presente Política, a la normativa aplicable o a derechos de terceros.' },
      ],
    },
    {
      id: 'inversion',
      number: '19',
      title: 'Publicidad vinculada a financiación e inversión',
      content: [
        { type: 'p', text: 'Atento a la naturaleza de los Servicios (inversión inmobiliaria, eventual aceptación de criptoactivos), LÓTUM observará especial cuidado en la publicidad que refiera a rentabilidad, riesgo, financiación o pagos en moneda extranjera/cripto:' },
        { type: 'ul', items: [
          'Incluirá advertencias sobre los riesgos inherentes a la inversión inmobiliaria.',
          'No prometerá rentabilidades garantizadas.',
          'Aclarará que no presta asesoramiento financiero ni intermedia en oferta pública de valores.',
          'Indicará la conveniencia de obtener asesoramiento profesional independiente.',
          'Cumplirá con las normativas BCRA, CNV (incluyendo el régimen PSAV — Res. Gral. CNV 994/2024) y UIF aplicables a la publicidad de productos financieros y vinculados a criptoactivos.',
          'En publicidad de financiamiento al comprador final, incluirá el Costo Financiero Total (CFT), la Tasa Nominal Anual (TNA) y la Tasa Efectiva Anual (TEA) cuando corresponda.',
        ]},
      ],
    },
    {
      id: 'accesibilidad',
      number: '20',
      title: 'Accesibilidad de la publicidad',
      content: [
        { type: 'p', text: 'LÓTUM procurará que su publicidad sea accesible a personas con discapacidad, incorporando progresivamente subtítulos en videos, descripciones alternativas en imágenes, contraste adecuado, lenguaje claro y demás buenas prácticas conforme a la normativa de accesibilidad (Ley 26.378 — Convención sobre los Derechos de las Personas con Discapacidad).' },
      ],
    },
    {
      id: 'archivo',
      number: '21',
      title: 'Archivo y conservación de piezas publicitarias',
      content: [
        { type: 'p', text: 'LÓTUM conservará un archivo de las piezas publicitarias difundidas, junto con sus fechas de publicación, canales utilizados y autorizaciones, por el plazo legal aplicable (mínimo CINCO (5) años), a los efectos de poder acreditar el cumplimiento de la normativa publicitaria ante autoridades competentes o frente a reclamos de consumidores.' },
      ],
    },
    {
      id: 'modificaciones',
      number: '22',
      title: 'Modificaciones a la política',
      content: [
        { type: 'p', text: 'LÓTUM podrá modificar la presente Política para adaptarla a cambios normativos, tecnológicos o de negocio. Las modificaciones serán notificadas con un preaviso mínimo de DIEZ (10) días corridos a través de la Plataforma. La continuación en el uso de los Servicios o en la actividad publicitaria implicará la aceptación de la versión vigente.' },
      ],
    },
    {
      id: 'contacto',
      number: '23',
      title: 'Contacto y denuncias',
      content: [
        { type: 'p', text: 'Para consultas, autorizaciones, denuncias de publicidad infractora o cualquier cuestión vinculada a la presente Política, los interesados podrán contactarse con:' },
        { type: 'ul', items: [
          'Correo electrónico: contacto@lotum.com.ar',
          'WhatsApp: +54 9 223 583 4453',
          'Denuncias de contenido infractor: formulario en la Plataforma',
          'Domicilio postal: Mar del Plata, Provincia de Buenos Aires.',
        ]},
      ],
    },
  ],
  closingBox: {
    title: 'Declaración final',
    text: 'LÓTUM ASUME EL COMPROMISO DE DESARROLLAR Y PROMOVER PRÁCTICAS PUBLICITARIAS RESPONSABLES, VERACES, RESPETUOSAS DE LA DIGNIDAD HUMANA Y DE LOS DERECHOS DE CONSUMIDORES Y USUARIOS, CUMPLIENDO ESTRICTAMENTE LA NORMATIVA VIGENTE Y FOMENTANDO UN ECOSISTEMA INMOBILIARIO Y DE INVERSIÓN TRANSPARENTE, COMPETITIVO Y CONFIABLE.',
  },
};

export default PUBLICIDAD_DATA;
